[build]
command = "pip install -r requirements.txt"

[deploy]
startCommand = "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn api_portofolio.wsgi"

[volumes]
"db" = "/app/db"  # Monte un volume persistant pour SQLite