# Generated by Django 6.0.1 on 2026-01-12 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_contrat', models.CharField(max_length=100, verbose_name='Type de contrat')),
                ('date_debut', models.DateTimeField(verbose_name='Date de début')),
                ('date_fin', models.DateTimeField(verbose_name='Date de fin')),
                ('nom_entreprise', models.CharField(max_length=100, verbose_name="Nom de l'entreprise")),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Expérience',
                'verbose_name_plural': 'Expérience',
            },
        ),
        migrations.CreateModel(
            name='Localisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pays', models.CharField(blank=True, max_length=100, null=True, verbose_name='Pays')),
                ('ville', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ville')),
                ('longitude', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Longitude')),
                ('latitude', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Latitude')),
                ('quartier', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Localisation',
                'verbose_name_plural': 'Localisations',
            },
        ),
        migrations.CreateModel(
            name='Prise_contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=100, verbose_name='Nom complet')),
                ('email', models.EmailField(max_length=254, verbose_name='Email du contact')),
                ('objet', models.CharField(max_length=100, verbose_name='Objet')),
                ('message', models.CharField(max_length=500, verbose_name='Message')),
            ],
            options={
                'verbose_name': 'Prise de contact',
                'verbose_name_plural': 'Prises de contact',
            },
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100, verbose_name='Titre')),
                ('Resume', models.CharField(max_length=100, verbose_name='Resume')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Image')),
                ('lien', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lien')),
            ],
            options={
                'verbose_name': ('Projet',),
                'verbose_name_plural': 'Projets',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(blank=True, max_length=100, null=True, verbose_name='Détail')),
                ('type_service', models.CharField(blank=True, max_length=100, null=True, verbose_name='Type')),
                ('outils', models.CharField(blank=True, max_length=100, null=True, verbose_name='Détail')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la plateforme')),
                ('lien', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lien social')),
            ],
            options={
                'verbose_name': ('Réseau social',),
                'verbose_name_plural': 'Réseaux sociaux',
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom Utilisateur')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom Utilisateur')),
                ('photo_profil', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Photo de profil')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Description')),
                ('age', models.CharField(blank=True, max_length=100, null=True, verbose_name='age')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('telephone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Téléphone')),
                ('lien_cv', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lien CV')),
                ('experience', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.experience')),
                ('localisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.localisation')),
                ('prise_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.prise_contact')),
                ('projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.projet')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.service')),
                ('sociallink', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.sociallink')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
            },
        ),
    ]
