# Generated by Django 6.0.1 on 2026-01-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_remove_utilisateur_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.CharField(max_length=200, verbose_name="description de l'éxpérience"),
        ),
    ]
