# Generated by Django 6.0.1 on 2026-01-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_experience_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Rôle'),
        ),
    ]
