# Generated by Django 6.0.1 on 2026-03-06 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_experience_role'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prise_contact',
            new_name='PriseContact',
        ),
        migrations.AlterModelOptions(
            name='projet',
            options={'verbose_name': 'Projet', 'verbose_name_plural': 'Projets'},
        ),
        migrations.AddField(
            model_name='service',
            name='nom',
            field=models.CharField(default=1, max_length=100, verbose_name='Nom du service'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='projets',
            field=models.ManyToManyField(blank=True, to='portfolio.projet'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='services',
            field=models.ManyToManyField(blank=True, to='portfolio.service'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='sociallinks',
            field=models.ManyToManyField(blank=True, to='portfolio.sociallink'),
        ),
    ]
