# Generated by Django 6.0.1 on 2026-03-06 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_rename_prise_contact_prisecontact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projet',
            name='Resume',
        ),
        migrations.AddField(
            model_name='projet',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='projet',
            name='gallery',
            field=models.JSONField(blank=True, null=True, verbose_name='Galerie images (JSON)'),
        ),
        migrations.AddField(
            model_name='projet',
            name='github_url',
            field=models.URLField(blank=True, null=True, verbose_name='GitHub URL'),
        ),
        migrations.AddField(
            model_name='projet',
            name='media_type',
            field=models.CharField(blank=True, choices=[('gallery', 'Gallery'), ('video', 'Video')], max_length=20, null=True, verbose_name='Type de média'),
        ),
        migrations.AddField(
            model_name='projet',
            name='media_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL Média (Vidéo ou Galerie)'),
        ),
        migrations.AddField(
            model_name='projet',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Rôle'),
        ),
        migrations.AddField(
            model_name='projet',
            name='tools',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Outils utilisés'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Image principale'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='lien',
            field=models.URLField(blank=True, null=True, verbose_name='Lien du projet'),
        ),
        migrations.AddField(
            model_name='projet',
            name='resume',
            field=models.CharField(default=2, max_length=200, verbose_name='Résumé'),
            preserve_default=False,
        ),
    ]
