# Generated by Django 6.0.1 on 2026-03-06 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_remove_projet_resume_projet_category_projet_gallery_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='outils',
        ),
        migrations.RemoveField(
            model_name='service',
            name='type_service',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='projets',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='services',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='sociallinks',
        ),
        migrations.AddField(
            model_name='experience',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='portfolio.utilisateur'),
        ),
        migrations.AddField(
            model_name='prisecontact',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages_recus', to='portfolio.utilisateur'),
        ),
        migrations.AddField(
            model_name='projet',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projets', to='portfolio.utilisateur'),
        ),
        migrations.AddField(
            model_name='service',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='portfolio.utilisateur'),
        ),
        migrations.AddField(
            model_name='sociallink',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sociallinks', to='portfolio.utilisateur'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='localisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.localisation'),
        ),
    ]
