# Generated by Django 6.0.1 on 2026-03-06 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_remove_service_outils_remove_service_type_service_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='localisation',
        ),
        migrations.AddField(
            model_name='localisation',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='localisations', to='portfolio.utilisateur'),
        ),
    ]
