# Generated by Django 6.0.1 on 2026-03-06 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_remove_utilisateur_localisation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de l’outil')),
            ],
        ),
        migrations.RemoveField(
            model_name='projet',
            name='tools',
        ),
        migrations.AddField(
            model_name='projet',
            name='tools',
            field=models.ManyToManyField(blank=True, related_name='projets', to='portfolio.tool', verbose_name='Outils utilisés'),
        ),
    ]
