# Generated by Django 6.0.1 on 2026-03-06 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_tool_remove_projet_tools_projet_tools'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=255)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills_fk', to='portfolio.utilisateur')),
            ],
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='utilisateurs', to='portfolio.skill', verbose_name='Compétences'),
        ),
    ]
