# Generated by Django 6.0.1 on 2026-03-06 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_skill_utilisateur_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='skills',
        ),
    ]
