# Generated by Django 6.0.3 on 2026-03-06 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_remove_utilisateur_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='copyright_author',
            field=models.CharField(blank=True, help_text='Nom qui apparaîtra dans le copyright du footer', max_length=200, null=True, verbose_name='Auteur copyright'),
        ),
    ]
