# Generated by Django 6.0.3 on 2026-03-06 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_projet_copyright_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='photo_intro',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name="Photo d'introduction"),
        ),
    ]
