# Generated by Django 6.0.3 on 2026-03-06 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_utilisateur_photo_intro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projet',
            name='gallery',
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Image')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='portfolio.projet')),
            ],
            options={
                'verbose_name': 'Image de galerie',
                'verbose_name_plural': 'Images de galerie',
            },
        ),
        migrations.AddField(
            model_name='projet',
            name='gallery',
            field=models.ManyToManyField(blank=True, related_name='projets', to='portfolio.galleryimage', verbose_name="Galerie d'images"),
        ),
    ]
