# Generated by Django 6.0.3 on 2026-03-06 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_remove_projet_gallery_galleryimage_projet_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='titles_text',
            field=models.TextField(blank=True, help_text='Ex: Future Software Engineer, Computer Science Student, Web Developer', null=True, verbose_name='Titres (séparés par des virgules)'),
        ),
    ]
