"""
Django settings for api_portofolio project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""


from pathlib import Path
import os
from decouple import config

BASE_DIR = Path(__file__).resolve().parent.parent

# Détection de l'environnement
IS_PRODUCTION = os.environ.get('RAILWAY_ENVIRONMENT_NAME') == 'production'

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# Configuration selon l'environnement
if IS_PRODUCTION:
    DEBUG = True
    ALLOWED_HOSTS = [
        '.railway.app',
        'portfolio-frontend-ecru-mu.vercel.app',
    ]
    
      # CORRECTION: Crée le dossier /app/db s'il n'existe pas
    db_path = '/app/db'
    if not os.path.exists(db_path):
        os.makedirs(db_path, exist_ok=True)
        print(f"📁 Dossier {db_path} créé")
    
    # Database pour production (SQLite avec volume persistant)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(db_path, 'db.sqlite3'),
        }
    }
    
    # CORS restreint en production
    CORS_ALLOW_ALL_ORIGINS = False
    CORS_ALLOWED_ORIGINS = [
        'https://portfolio-frontend-ecru-mu.vercel.app',
    ]
    
    # CSRF trusted origins
    CSRF_TRUSTED_ORIGINS = [
        'https://*.railway.app',
        'https://portfolio-backend-production-38e9.up.railway.app',
        'https://portfolio-frontend-ecru-mu.vercel.app',
    ]
    # Force Django à vérifier la connexion avant chaque requête
    DATABASES['default']['CONN_MAX_AGE'] = 0  # Pas de connexion persistante
    DATABASES['default']['OPTIONS'] = {
        'timeout': 20,
        'check_same_thread': False,  # Important pour SQLite en production
    }
    
else:
    # Développement local
    DEBUG = True
    ALLOWED_HOSTS = ["127.0.0.1", "localhost"]
    
    # Database locale
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
    
    # CORS permissif en développement
    CORS_ALLOW_ALL_ORIGINS = True
    CSRF_TRUSTED_ORIGINS = []

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'corsheaders',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'portfolio',
    'rest_framework',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
]


MIDDLEWARE += [
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'api_portofolio.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'api_portofolio.wsgi.application'

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]  # Vos fichiers statiques
STATIC_ROOT = BASE_DIR / 'staticfiles'     # Pour collectstatic


# Ajout de WhiteNoise seulement en production
if IS_PRODUCTION:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
   
    MIDDLEWARE.append('whitenoise.middleware.WhiteNoiseMiddleware')




# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / "media"

# REST Framework
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ]
}

# Configuration email
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
EMAIL_HOST = config('EMAIL_HOST')
EMAIL_PORT = config('EMAIL_PORT', cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', cast=bool)
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL')